# Generated by Django 5.2.5 on 2025-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('superadmin', 'Super Admin')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('standard', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(blank=True, choices=[('primary', 'Primary Section'), ('secondary', 'Secondary Section')], max_length=100, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='application_docs/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
